name: Notes API CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '6.0'

      - name: Restore
        run: dotnet restore NotesAPI/NotesAPI.csproj

      - name: Build
        run: dotnet build NotesAPI/NotesAPI.csproj --no-restore

      - name: Publish
        run: dotnet publish NotesAPI/NotesAPI.csproj -c Release -o output

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: notes-api
          path: output
